project:
  type: website
  output-dir: docs

website:
  title: "Alvin Bong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: experience/index.qmd
        text: Experience
      - href: cv.pdf
        text: CV

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
  
editor: visual

